channels:
  - conda-forge
  - defaults
dependencies:
  - pandas
  - matplotlib
  - control
  - scipy
  - pathlib
  - numpy
  - tomli
  - sphinx
  - furo
  - sphinx-toolbox
  - sphinx-autodoc-typehints
  - pytest
  - mypy
  - black
  - flake8
  - coverage
  - grayskull
  - h5py
