# CI/CD pipeline
name: Fixed environment

on:
  push:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Here we use a freeze file so we are 100% sure that if there is any failure
  # is because of dymoval itself and not because of some weird dependency
  # stuff
  pip_tests:
    name: Tests with pip
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]


    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4.6.0
        with:
            python-version: '3.11'

      - name: Install dependencies (pip)
        run: |
          python -m pip install -r pip_freeze_py311.txt
          python -m pip install pytest
          python -m pip install .

      - name: Run tests (pytest)
        run: |
          pytest .

   # conda_tests:
   #   # Same as before but for conda
   #   name: Tests with conda
   #   runs-on: ${{ matrix.os }}
   #   strategy:
   #     fail-fast: false
   #     matrix:
   #       os: ["ubuntu-latest", "macos-latest", "windows-latest"]
   #       python-version: "3.11"

   #   steps:
   #     - name: Checkout
   #       uses: actions/checkout@v3

  #     - name: Conda setup
  #       uses: conda-incubator/setup-miniconda@v2
  #       with:
  #         python-version: "3.11"
  #         mamba-version: "*"
  #         channels: conda-forge,defaults
  #         channel-priority: true
  #         environment-file: ./conda_freeze_py311.yml

  #     - name: Install dymoval through pip
  #       shell: bash -l {0}
  #       run: |
  #       # TODO replace pip install with conda install xx.tar.gz built
  #       # through conda build if possible
  #         conda install pytest
  #         python -m pip install .

  #     - name: Run tests (pytest)
  #       shell: bash -l {0}
  #       run: |
  #         pytest .
